name: debt_smart_ar
description: دفتر الديون الذكي - Flutter Android direct APK
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  intl: ^0.20.2

flutter:
  uses-material-design: true
